CREATE TABLE SHELTERS (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NAME VARCHAR  NOT NULL,
                        SHELTERTYPE INT NOT NULL, --enum ShelterType
                        ADDRESS VARCHAR NOT NULL,
                        OPENINGHOURS VARCHAR NOT NULL,
                        CONTACTDETAILS VARCHAR
);

CREATE TABLE IF NOT EXISTS PETS (
                                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    PETTYPE INT NOT NULL, -- enum PetType
                                    NAME VARCHAR,
                                    SEX INT NOT NULL   -- enum Sex
);