CREATE TABLE Request(
                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_name VARCHAR,
                       result VARCHAR


);


CREATE TABLE Client (
                        id BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        chat_id BIGINT,
                        name VARCHAR NOT NULL ,
                        age INTEGER,
                        telephone VARCHAR NOT NULL,
                        address VARCHAR
);
CREATE TABLE Attachment(
                              ATTACHMENT_ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              ATTACH_TITLE VARCHAR ,
                              UPLOAD_DATE TIMESTAMP,
                              EXTENSION_FILE VARCHAR,
                              DOWNLOAD_LINK VARCHAR

);