CREATE TABLE SHELTERS (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NAME VARCHAR  NOT NULL,
                        SHELTERTYPE INT NOT NULL, --enum ShelterType
                        ADDRESS VARCHAR NOT NULL,
                        OPENINGHOURS VARCHAR NOT NULL,
                        CONTACTDETAILS VARCHAR
);

CREATE TABLE IF NOT EXISTS PETS (
                                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    PETTYPE INT NOT NULL, -- enum PetType
                                    NAME VARCHAR,
                                    SEX INT NOT NULL   -- enum Sex
);
CREATE TABLE Volunteer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          userName VARCHAR  NOT NULL
);
CREATE TABLE IF NOT EXISTS Client_Status (
                                    ID BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    chat_id BIGINT,
                                    client_Status VARCHAR,
                                    click_Counter_Cat INT NOT NULL,
                                    click_Counter_Dog INT NOT NULL
);