CREATE TABLE REPORT (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        TOTAL_PASSES_ATTACH INTEGER,
                        TOTAL_PASSES_QUEST INTEGER,
                        REPO_ATTACH_DAY1 INTEGER,
                        REPO_ATTACH_DAY2 INTEGER,
                        REPO_ATTACH_DAY3 INTEGER,
                        ATTACH_DAY_ROW INTEGER,
                        REPO_QUEST_DAY1 INTEGER,
                        REPO_QUEST_DAY2 INTEGER,
                        REPO_QUEST_DAY3 INTEGER,
                        QUEST_DAY_ROW INTEGER
);
CREATE TABLE CLIENT (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        FULL_NAME VARCHAR  NOT NULL,
                        AGE INTEGER,
                        telephone INTEGER NOT NULL,
                        ADDRESS VARCHAR,
                        PET VARCHAR
);
CREATE TABLE Attachment(
                              ATTACHMENT_ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              ATTACH_TITLE VARCHAR ,
                              UPLOAD_DATE TIMESTAMP,
                              EXTENSION_FILE VARCHAR,
                              DOWNLOAD_LINK VARCHAR,
                              QUEST VARCHAR
);